'use client'
import { useEffect,useRef,useState } from 'react'
import { useParams } from 'next/navigation'
import Nav from '../../../components/Nav'
import { api } from '../../../lib/api'
function Pill({children}:{children:any}){return <span className="badge bg-gray-100 text-gray-700">{children}</span>}
export default function KitPage(){
 const {id}=useParams<{id:string}>(); const [kit,setKit]=useState<any>(null); const [tab,setTab]=useState('overview'); const [err,setErr]=useState(''); const [saving,setSaving]=useState(false); const [practiceIndex,setPracticeIndex]=useState(0); const [revealed,setRevealed]=useState(false); const [busy,setBusy]=useState(''); const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null)
 async function load(){try{const x=await api<any>(`/kits/${id}`);setKit(x.kit);setErr('')}catch(e){setErr(e instanceof Error?e.message:'Failed')}}
 useEffect(()=>{load()},[id]); useEffect(()=>{if(kit?.generationStatus?.status==='processing'){const t=setInterval(load,1800);return()=>clearInterval(t)}},[kit?.generationStatus?.status])
 async function save(next:any){setSaving(true);try{const x=await api<any>(`/kits/${id}`,{method:'PATCH',body:JSON.stringify(next)});setKit(x.kit)}catch(e){setErr(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 function scheduleSave(next:any){if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{void save(next)},500)}
 async function regen(section:string){setBusy(section);try{const x=await api<any>(`/kits/${id}/regenerate`,{method:'POST',body:JSON.stringify({section})});setKit(x.kit)}catch(e){setErr(e instanceof Error?e.message:'Regeneration failed')}finally{setBusy('')}}
 if(!kit)return (<><Nav/><main className="max-w-4xl mx-auto p-6"><div className={`card p-6 ${err?'text-red-700':''}`}>{err||'Loading…'}</div></main></>);
 const gs=kit.generationStatus||{}; if(gs.status==='processing')return (<><Nav/><main className="max-w-3xl mx-auto p-6"><div className="card p-7"><div className="text-2xl font-black">Generating your kit</div><p className="text-gray-500 mt-2">{gs.stage}</p><div className="w-full h-3 bg-gray-100 rounded-full mt-5 overflow-hidden"><div className="h-full bg-gray-900" style={{width:`${gs.progress||5}%`}}/></div><div className="text-sm mt-3">{gs.progress||0}%</div></div></main></>);
 const questions=kit.questions||[]; const confidenceByCard=new Map<string, number>((kit.practice||[]).map((x:any):[string, number]=>[x.flashcardId,x.confidence])); const orderedCards=[...(kit.flashcards||[])].sort((a:any,b:any)=>(confidenceByCard.get(a.id)??0)-(confidenceByCard.get(b.id)??0)); const card=orderedCards[practiceIndex%Math.max(orderedCards.length,1)]
 const must=kit.role?.requirements?.filter((r:any)=>r.priority==='must')||[]; const uncovered=new Set(kit.coverage?.uncovered_requirement_ids||[]); const covered=must.filter((r:any)=>!uncovered.has(r.id)).length
 async function rate(v:number){await api(`/kits/${id}/practice`,{method:'POST',body:JSON.stringify({flashcardId:card.id,confidence:v})});setRevealed(false);setPracticeIndex(i=>i+1);load()}
 function updateQuestion(q:any,field:string,value:string){const next=questions.map((x:any)=>x.id===q.id?{...x,[field]:value,state:'edited'}:x);const updated={...kit,questions:next};setKit(updated);scheduleSave(updated)}
 async function moveQuestion(i:number,d:number){const a=[...questions],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setKit({...kit,questions:a});await save({...kit,questions:a})}
 async function deleteQuestion(qid:string){const next=questions.filter((q:any)=>q.id!==qid);setKit({...kit,questions:next});await save({...kit,questions:next})}
 async function addQuestion(){const q={id:`q-manual-${Date.now()}`,requirement_ids:must[0]?[must[0].id]:[],category:'technical',prompt:'New interview question',answer_outline:'Add your answer outline.',difficulty:2,state:'edited'};const next=[...questions,q];setKit({...kit,questions:next});await save({...kit,questions:next})}
 function editBrief(field:string,value:string){const next={...kit.company_brief,[field]:value};const updated={...kit,company_brief:next};setKit(updated);scheduleSave(updated)}
 async function addCard(){const f={id:`f-manual-${Date.now()}`,front:'New flashcard',back:'Add the key answer here.',requirement_ids:must[0]?[must[0].id]:[],state:'edited'};const next=[...(kit.flashcards||[]),f];setKit({...kit,flashcards:next});await save({...kit,flashcards:next})}
 async function deleteCard(fid:string){const next=(kit.flashcards||[]).filter((f:any)=>f.id!==fid);setKit({...kit,flashcards:next});await save({...kit,flashcards:next})}
 return <><Nav/><main className="max-w-7xl mx-auto p-5 md:p-7 space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex gap-2 items-center"><h1 className="text-3xl font-black">{kit.role?.title||'Interview Kit'}</h1><Pill>{kit.source?.company}</Pill></div><p className="text-gray-500 mt-1">{kit.source?.company_url}</p></div><div className="text-sm text-gray-500">{saving?'Saving…':'Saved'}</div></div>{gs.status==='failed'&&<div className="p-4 rounded-xl bg-red-50 text-red-800"><b>Generation failed.</b> {gs.error?.message||'The pipeline could not produce a complete kit.'}</div>}{err&&<div className="p-3 rounded-lg bg-red-50 text-red-700">{err}</div>}<div className="flex flex-wrap gap-2">{['overview','questions','flashcards','schedule','practice'].map(x=><button key={x} onClick={()=>setTab(x)} className={`btn ${tab===x?'btn-primary':'btn-secondary'}`}>{x}</button>)}</div>
 {tab==='overview'&&<section className="grid lg:grid-cols-2 gap-5"><div className="card p-5"><div className="flex justify-between gap-3"><h2 className="font-black text-xl">Company brief</h2><button className="btn btn-secondary" onClick={()=>regen('company_brief')}>{busy==='company_brief'?'…':'Regenerate'}</button></div><input className="input mt-4 font-bold" value={kit.company_brief?.summary||''} onChange={e=>editBrief('summary',e.target.value)}/><textarea className="input mt-3 min-h-28" value={kit.company_brief?.what_they_do||''} onChange={e=>editBrief('what_they_do',e.target.value)}/><div className="mt-4 text-xs text-gray-500">Sources: {(kit.company_brief?.sources||[]).length}</div></div><div className="card p-5"><h2 className="font-black text-xl">Coverage</h2><div className="text-4xl font-black mt-3">{covered}/{must.length}</div><div className="text-gray-500">must-have requirements covered</div><div className="mt-4">Coverage passes: {kit.coverage?.passes}</div>{uncovered.size>0&&<div className="mt-3 text-red-700 text-sm">Still uncovered: {[...uncovered].join(', ')}</div>}</div><div className="card p-5 lg:col-span-2"><h2 className="font-black text-xl">Role requirements</h2><div className="mt-4 grid md:grid-cols-2 gap-3">{(kit.role?.requirements||[]).map((x:any)=><div key={x.id} className="border rounded-xl p-4"><div className="flex justify-between"><b>{x.id}</b><Pill>{x.priority}</Pill></div><div className="mt-2">{x.text}</div><div className="text-xs text-gray-500 mt-2">{x.kind}</div></div>)}</div></div></section>}
 {tab==='questions'&&<section className="card p-5"><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="font-black text-xl">Question bank</h2><div className="flex flex-wrap gap-2"><button className="btn btn-secondary" onClick={addQuestion}>+ Add question</button>{['technical','behavioural','system-design','company-fit'].map(c=><button key={c} className="btn btn-secondary" onClick={()=>regen(c)}>{busy===c?'…':`Regenerate ${c}`}</button>)}</div></div><div className="mt-5 space-y-4">{questions.map((q:any,i:number)=><div key={q.id} className="border rounded-xl p-4"><div className="flex justify-between gap-3"><div className="flex gap-2 items-center"><Pill>{q.category}</Pill><Pill>difficulty {q.difficulty}</Pill>{q.state==='edited'&&<Pill>edited</Pill>}</div><div className="flex gap-1"><button className="btn btn-secondary" onClick={()=>moveQuestion(i,-1)}>↑</button><button className="btn btn-secondary" onClick={()=>moveQuestion(i,1)}>↓</button><button className="btn btn-danger" onClick={()=>deleteQuestion(q.id)}>Delete</button></div></div><select className="input mt-3" value={q.category} onChange={e=>updateQuestion(q,'category',e.target.value)}><option>technical</option><option>behavioural</option><option>system-design</option><option>company-fit</option></select><textarea aria-label="Question prompt" className="input mt-3 min-h-20" value={q.prompt} onChange={e=>updateQuestion(q,'prompt',e.target.value)}/><textarea aria-label="Answer outline" className="input mt-3 min-h-24" value={q.answer_outline} onChange={e=>updateQuestion(q,'answer_outline',e.target.value)}/><div className="text-xs text-gray-500 mt-2">Covers: {q.requirement_ids?.join(', ')}</div></div>)}</div></section>}
 {tab==='flashcards'&&<section className="card p-5"><div className="flex justify-between"><h2 className="font-black text-xl">Flashcards</h2><button className="btn btn-secondary" onClick={addCard}>+ Add card</button></div><div className="mt-4 grid md:grid-cols-2 gap-4">{(kit.flashcards||[]).map((f:any)=><div key={f.id} className="border rounded-xl p-4"><div className="flex justify-end"><button className="btn btn-danger" onClick={()=>deleteCard(f.id)}>Delete</button></div><input aria-label="Flashcard front" className="input font-bold mt-2" value={f.front} onChange={e=>setKit({...kit,flashcards:kit.flashcards.map((x:any)=>x.id===f.id?{...x,front:e.target.value,state:'edited'}:x)})}/><textarea aria-label="Flashcard back" className="input mt-3 min-h-28" value={f.back} onChange={e=>setKit({...kit,flashcards:kit.flashcards.map((x:any)=>x.id===f.id?{...x,back:e.target.value,state:'edited'}:x)})}/><button className="btn btn-secondary mt-3" onClick={()=>save({...kit})}>Save card</button></div>)}</div></section>}
 {tab==='schedule'&&<section className="card p-5"><div className="flex justify-between"><h2 className="font-black text-xl">Study schedule</h2><button className="btn btn-secondary" onClick={()=>regen('schedule')}>{busy==='schedule'?'…':'Regenerate schedule'}</button></div><div className="mt-5 grid md:grid-cols-2 gap-4">{(kit.schedule?.days||[]).map((d:any)=><div key={d.day} className="border rounded-xl p-4"><div className="flex justify-between"><b>Day {d.day}</b><Pill>{d.minutes} min</Pill></div><div className="mt-2 font-bold">{d.focus}</div><div className="mt-3 text-sm text-gray-600">{d.question_ids.join(' · ')||'Review/reflection'}</div></div>)}</div></section>}
 {tab==='practice'&&<section className="card p-6 max-w-2xl mx-auto"><div className="text-sm text-gray-500">Flashcard {orderedCards.length?((practiceIndex%orderedCards.length)+1):0} / {orderedCards.length}</div>{card?<><div className="text-2xl font-black mt-5">{card.front}</div>{revealed?<div className="mt-5 p-4 bg-gray-50 rounded-xl">{card.back}</div>:<button className="btn btn-primary mt-5" onClick={()=>setRevealed(true)}>Reveal answer</button>}{revealed&&<div className="mt-6"><div className="font-bold">How confident were you?</div><div className="flex flex-wrap gap-2 mt-3">{[1,2,3,4,5].map(v=><button className="btn btn-secondary" key={v} onClick={()=>rate(v)}>{v}</button>)}</div></div>}</>:<div className="mt-8 text-gray-500">No flashcards generated.</div>}</section>}
 </main></>
}
